name: 'Preview Pull Requests in Kubernetes'
description: 'Deploy preview of Pull Requests to Kubernetes using Helm charts'
author: 'vendanor'

branding:
  icon: "box"
  color: "orange"

inputs:
  token:
    description: "Your Github token"
    default: $
    required: true
  probe:
    description: "Set to true if you only want to probe for information"
    default: "false"
    required: false
  docker-file:
    required: false
    default: "Dockerfile"
    description: "Dockerfile to build, tag with preview metadata and publish to container registry"
  docker-registry:
    required: false
    default: "ghcr.io"
    description: "Docker container registry. Defaults to Github container registry"
  docker-username:
    required: false
    description: "Username docker container registry, ghcr? github.repository_owner"
  docker-password:
    required: false
    description: "Password docker container registry"
  docker-image-name:
    required: false
    description: "Example vn-my-app"
  docker-organization:
    required: false
    default: "vendanor"
    description: "Organization used to construct docker registry url"
  docker-tag-major:
    required: false
    default: "1.0"
    description: "Major tag used when tagging docker images, example: 1.0"
  docker-pullsecret:
    required: false
    description: "Docker pullsecret to use when pulling docker images from registry when deploying helm chart"

  helm-namespace:
    required: false
    default: "preview"
    description: "Helm namespace where Helm releases are published. Also used as k8s namespace!"
  helm-repo-url:
    required: false
    description: "Helm chart repo. If supplied, Helm charts are published here"
  helm-organization:
    required: false
    default: "vendanor"
    description: "Used when pushing helm chart to helm chart repo"
  helm-repo-user:
    required: false
    default: "vendanor"
    description: "Username to helm chart repo if you want to publish chart"
  helm-repo-password:
    required: false
    description: "Helm chart repo password if you want tp publish chart"
  helm-chart:
    required: false
    description: "Path to helm chart in repo, example: charts/vn-my-app"
  helm-tag-major:
    required: true
    default: "1.0"
    description: "Major tag when tagging helm chart previews, example: 1.0"
  helm-remove-preview-charts:
    required: true
    default: "true"
    description: "Remove all preview helm charts when calling command remove"

  helm-key-appname:
    required: true
    default: "appname"
    description: "The key to set in your helm chart to set when installing preview"
  helm-key-namespace:
    required: true
    default: "namespace"
    description: "k8s namespace key to override"
  helm-key-image:
    required: true
    default: "image"
    description: "The key to set in your helm chart to set when installing preview"
  helm-key-pullsecret:
    required: true
    default: "pullsecret"
    description: "The key to set in your helm chart to set when installing preview"
  helm-key-url:
    required: true
    default: "url"
    description: "The key to set in your helm chart to set when installing preview"
  helm-key-containersuffix:
    required: true
    default: "containersuffix"
    description: "The key to set in your helm chart to set when installing preview"
  helm-key-cluster-issuer:
    required: true
    default: "clusterIssuer"
    description: "The key to set in your helm chart to set when installing preview"
  helm-key-tls-secret-name:
    required: true
    default: "tlsSecretName"
    description: "The key to set in your helm chart to set when installing preview"

  # idea, use this for 1) docker image url 2) helm chart url 3) preview url?  => rename to preview-name?
  app-name:
    required: true
    description: "App name used in preview url."
  hash-salt:
    required: false
    default: "salt"
    description: "Secret salt used to generate preview hash"
  base-url:
    required: false
    default: "pr.st.vendanor.com"
    description: "Base preview url, example preview.domain.com"
  cluster-issuer:
    required: true
    default: vn-letsencrypt-preview-issuer
    description: "Name of cluster issuer to use"
  tls-secret-name:
    required: true
    default: vn-preview-wild
    description: "Certificate secret name. Use a shared name for wildcard certs"
  helm-values:
    required: false
    description: "Extra values to pass to helm upgrade --set. Example: key1=val1,key2=val2"
  wait:
    required: false
    default: "false"
    description: "Waits until deployment is successful, pods are running, etc. before marking the release as successful"

outputs:
  previewUrl:
    description: "Complete url to preview"
  dockerImageVersion:
    description: "Docker image name including tags (semver)"
  helmReleaseName:
    description: "Helm chart release version including tags (semver)"
  success:
    description: "was everything successful or not."
  isPreviewEnabled:
    description: "Returns true if user has requested a preview. Checks hidden value in comment"
  isBot:
    description: "Returns true if action was triggered by a bot"
  isComment:
    description: "Returns true if action was triggered by a comment"
  isValidCommand:
    description: "Returns true if comment contains a valid command"
  isAddPreviewPending:
    description: "Returns true if a preview will be deployed"
  isRemovePreviewPending:
    description: "Returns true if a preview will be removed"

runs:
  using: 'node12'
  main: 'dist/index.js'
